services:
  app:
    build: ./docker
    ports:
      - "8888:8888"
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - ./docker:/docker
